mod postgres
mod localstack
mod aws

# lists all recipes
@default:
    echo "--------------------"
    echo "- ROOT"
    echo "--------------------"
    just -gl
    echo "--------------------"
    echo "- AWS"
    echo "--------------------"
    just -gl aws
    echo "--------------------"
    echo "- LOCALSTACK"
    echo "--------------------"
    just -gl localstack
    echo "--------------------"
    echo "- POSTGRES"
    echo "--------------------"
    just -gl postgres